version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/sqlite/database.sqlite:/var/www/html/database/database.sqlite
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sqlite:
